### ISSUE TITLE
Build failures on Go workflow and Jenkins

### ISSUE THREAD

**Issue by willeagren** [Ignalina/alloy#19]
For some reason the builds fail, complaining about undefined reference to the function `callwithschema` which is clearly defined. And it works on 3 of my systems, each with different Go versions and CPU architectures. Is there something I am missing clearly? If you clone and run the Makefile the build passes, and if you just build go locally `go build ./...` it also works.

I need someone smart to help me :)

``` 
Branch indexing
Started by user [willeagren](https://jenkins.x14.se/user/willeagren)
09:45:26 Connecting to https://api.github.com/ with no credentials, anonymous access
Obtained Jenkinsfile from 5ce762691d13bf24c449b41301e2ca050aaa3ddb
[Pipeline] Start of Pipeline
[Pipeline] node
Running on [speedagent](https://jenkins.x14.se/manage/computer/speedagent/) in /var/jenkins/workspace/alloy_main
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE
Warning: CredentialId "github" could not be found.
Fetching changes from the remote Git repository
Cleaning workspace
Fetching without tags
Checking out Revision 5ce762691d13bf24c449b41301e2ca050aaa3ddb (main)
Commit message: "Merge pull request #18 from Ignalina/feature/workflows"
 > git rev-parse --resolve-git-dir /var/jenkins/workspace/alloy_main/.git # timeout=10
 > git config remote.origin.url https://github.com/Ignalina/alloy.git # timeout=10
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/Ignalina/alloy.git
 > git --version # timeout=10
 > git --version # 'git version 2.34.1'
 > git fetch --no-tags --force --progress -- https://github.com/Ignalina/alloy.git +refs/heads/main:refs/remotes/origin/main # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 5ce762691d13bf24c449b41301e2ca050aaa3ddb # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D main # timeout=10
 > git checkout -b main 5ce762691d13bf24c449b41301e2ca050aaa3ddb # timeout=10
 > git rev-list --no-walk b722612a295211be87cfb473e6d7cf0e63139286 # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] sh
+ whoami
jenkins
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/var/lib/jenkins/.cargo/bin
+ go version
go version go1.18.5 linux/amd64
+ make
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.44
   Compiling unicode-ident v1.0.4
   Compiling quote v1.0.21
   Compiling syn v1.0.101
   Compiling memchr v2.5.0
   Compiling libc v0.2.133
   Compiling static_assertions v1.1.0
   Compiling serde v1.0.145
   Compiling cfg-if v1.0.0
   Compiling thiserror v1.0.37
   Compiling ryu v1.0.11
   Compiling serde_json v1.0.85
   Compiling hashbrown v0.12.3
   Compiling ppv-lite86 v0.2.16
   Compiling regex-automata v0.1.10
   Compiling serde_derive v1.0.145
   Compiling lazy_static v1.4.0
   Compiling itoa v0.4.8
   Compiling bitflags v1.3.2
   Compiling smallvec v1.9.0
   Compiling itoa v1.0.3
   Compiling regex-syntax v0.6.27
   Compiling iana-time-zone v0.1.50
   Compiling hex v0.4.3
   Compiling half v1.8.2
   Compiling lexical-util v0.8.5
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling num-bigint v0.4.3
   Compiling num-rational v0.4.1
   Compiling num-iter v0.1.43
   Compiling indexmap v1.9.1
   Compiling lexical-write-integer v0.8.5
   Compiling lexical-parse-integer v0.8.6
   Compiling lexical-write-float v0.8.5
   Compiling lexical-parse-float v0.8.5
   Compiling csv-core v0.1.10
   Compiling aho-corasick v0.7.19
   Compiling getrandom v0.2.7
   Compiling rand_core v0.6.4
   Compiling lexical-core v0.8.5
   Compiling regex v1.6.0
   Compiling rand_chacha v0.3.1
   Compiling num-complex v0.4.2
   Compiling rand v0.8.5
   Compiling chrono v0.4.22
   Compiling bstr v0.2.17
   Compiling csv v1.1.6
   Compiling num v0.4.0
   Compiling thiserror-impl v1.0.37
   Compiling multiversion-macros v0.6.1
   Compiling flatbuffers v2.0.0
   Compiling multiversion v0.6.1
   Compiling arrow v9.1.0
   Compiling impl v0.1.0 (/var/jenkins/workspace/alloy_main/lib/impl)
    Finished release [optimized] target(s) in 45.54s
go build ./...
# github.com/ignalina/alloy/api
/usr/bin/ld: $WORK/b001/_x002.o: in function `_cgo_2bcce2044036_Cfunc_callwithschema':
/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `callwithschema'
collect2: error: ld returned 1 exit status
make: *** [Makefile:12: build-go] Error 2
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 2

Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected


GitHub has been notified of this commit’s build result

Finished: FAILURE
```

**Comment by Ignalina** [comment]
Lets skip the makefile :)
Transfer the step to an bash script called buildall.sh and  edit jenkins ”sh buildall.sh” via link below
https://jenkins.x14.se/blue/organizations/jenkins/alloy/detail/main/33/pipeline/

Skickat från min iPhone

1 okt. 2022 kl. 11:53 skrev Wilhelm Ågren ***@***.***>:

﻿

For some reason the builds fail, complaining about undefined reference to the function callwithschema which is clearly defined. And it works on 3 of my systems, each with different Go versions and CPU architectures. Is there something I am missing clearly? If you clone and run the Makefile the build passes, and if you just build go locally go build ./... it also works.

I need someone smart to help me :)

Branch indexing
Started by user [willeagren](https://jenkins.x14.se/user/willeagren)
09:45:26 Connecting to https://api.github.com/ with no credentials, anonymous access
Obtained Jenkinsfile from 5ce762691d13bf24c449b41301e2ca050aaa3ddb
[Pipeline] Start of Pipeline
[Pipeline] node
Running on [speedagent](https://jenkins.x14.se/manage/computer/speedagent/) in /var/jenkins/workspace/alloy_main
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE
Warning: CredentialId "github" could not be found.
Fetching changes from the remote Git repository
Cleaning workspace
Fetching without tags
Checking out Revision 5ce762691d13bf24c449b41301e2ca050aaa3ddb (main)
Commit message: "Merge pull request #18 from Ignalina/feature/workflows"
 > git rev-parse --resolve-git-dir /var/jenkins/workspace/alloy_main/.git # timeout=10
 > git config remote.origin.url https://github.com/Ignalina/alloy.git # timeout=10
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Fetching upstream changes from https://github.com/Ignalina/alloy.git
 > git --version # timeout=10
 > git --version # 'git version 2.34.1'
 > git fetch --no-tags --force --progress -- https://github.com/Ignalina/alloy.git +refs/heads/main:refs/remotes/origin/main # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 5ce762691d13bf24c449b41301e2ca050aaa3ddb # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D main # timeout=10
 > git checkout -b main 5ce762691d13bf24c449b41301e2ca050aaa3ddb # timeout=10
 > git rev-list --no-walk b722612a295211be87cfb473e6d7cf0e63139286 # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] sh
+ whoami
jenkins
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/var/lib/jenkins/.cargo/bin
+ go version
go version go1.18.5 linux/amd64
+ make
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.44
   Compiling unicode-ident v1.0.4
   Compiling quote v1.0.21
   Compiling syn v1.0.101
   Compiling memchr v2.5.0
   Compiling libc v0.2.133
   Compiling static_assertions v1.1.0
   Compiling serde v1.0.145
   Compiling cfg-if v1.0.0
   Compiling thiserror v1.0.37
   Compiling ryu v1.0.11
   Compiling serde_json v1.0.85
   Compiling hashbrown v0.12.3
   Compiling ppv-lite86 v0.2.16
   Compiling regex-automata v0.1.10
   Compiling serde_derive v1.0.145
   Compiling lazy_static v1.4.0
   Compiling itoa v0.4.8
   Compiling bitflags v1.3.2
   Compiling smallvec v1.9.0
   Compiling itoa v1.0.3
   Compiling regex-syntax v0.6.27
   Compiling iana-time-zone v0.1.50
   Compiling hex v0.4.3
   Compiling half v1.8.2
   Compiling lexical-util v0.8.5
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling num-bigint v0.4.3
   Compiling num-rational v0.4.1
   Compiling num-iter v0.1.43
   Compiling indexmap v1.9.1
   Compiling lexical-write-integer v0.8.5
   Compiling lexical-parse-integer v0.8.6
   Compiling lexical-write-float v0.8.5
   Compiling lexical-parse-float v0.8.5
   Compiling csv-core v0.1.10
   Compiling aho-corasick v0.7.19
   Compiling getrandom v0.2.7
   Compiling rand_core v0.6.4
   Compiling lexical-core v0.8.5
   Compiling regex v1.6.0
   Compiling rand_chacha v0.3.1
   Compiling num-complex v0.4.2
   Compiling rand v0.8.5
   Compiling chrono v0.4.22
   Compiling bstr v0.2.17
   Compiling csv v1.1.6
   Compiling num v0.4.0
   Compiling thiserror-impl v1.0.37
   Compiling multiversion-macros v0.6.1
   Compiling flatbuffers v2.0.0
   Compiling multiversion v0.6.1
   Compiling arrow v9.1.0
   Compiling impl v0.1.0 (/var/jenkins/workspace/alloy_main/lib/impl)
    Finished release [optimized] target(s) in 45.54s
go build ./...
# github.com/ignalina/alloy/api
/usr/bin/ld: $WORK/b001/_x002.o: in function `_cgo_2bcce2044036_Cfunc_callwithschema':
/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `callwithschema'
collect2: error: ld returned 1 exit status
make: *** [Makefile:12: build-go] Error 2
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 2

Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected


GitHub has been notified of this commit’s build result

Finished: FAILURE

**Comment by willeagren** [comment]
I dont think skipping the Makefile is necessarily better, but yes I agree that a simple bash script could be simpler. But the problem is still that with the Makefile the Go code builds as it should, but on the github/workflows it fails. It could be some checkout/@v3 thing that should be defined as something else. Will investigate.

**Comment by Ignalina** [comment]
Works on jenkins now with the Makefile ,,, It was an "old" Go 18.5 on jenkins and i upgraded it to GO 19.1

**Comment by Ignalina** [comment]
Keeping makefil abit , it was GO 19+ needed.   Perhaps its CGO is better , a wild guess
