### ISSUE TITLE
Make a cool logo for alloy? 

### ISSUE THREAD

**Issue by willeagren** [Ignalina/alloy#25]
I was thinking we could make a simple, but cool, looking logo for the README that basically says "alloy" or something. Nothing fancy. There are a lot of free online tools that generate for you, i've used those before. 

Could present some examples in this issue thread.

**Comment by Ignalina** [comment]
Cool , go for it !

Im still thinking of trying out https://www.youtube.com/watch?v=YwDj4bs4bSY   for the Thund (=River in old Norse Myth) project.   i wonder if the Blender engine would manage 2 streams with different colours/materials ..as a kind of "alloy" .. or perhas  "kopplingen" in a car is a different idea .. what is the name in english for "koppling" ?  .. transmission ??

**Comment by willeagren** [comment]
Cool! Koppling is clutch in english

**Comment by willeagren** [comment]
@Ignalina latest commit on branch feature/readme has a logo. Check it out!
