### ISSUE TITLE
Approach to get it up and running

### ISSUE THREAD

**Issue by willeagren** [Ignalina/alloy#38]
I think that to actually see if the 'bridge' between go and Rust works as it should, which it kinda does; we need to read a real array or schema from file, read it in Go, convert all fields to the Cstruct and then pass it as we do. 

@Ignalina  do you know how to write a REAL/accurate schema to file that we can use for this?

If you see the latest commit on branch rewrite/all , compile and run it you will see that it atempts to convert to Schema in Rust, but the C struct is invalid format. Something I'm doing with the export is wrong. Maybe it will be solved if we give it a real schema...

ALso, will try with arrow2 functions for importing the schema; maybe that will work.

Have a good weekend, sent from a boat :boat:

**Comment by willeagren** [comment]
With arrow2 it understand the ffi_ArrowSchema pointer!!! It prints the schema. Now to just understand how to access the fields in the schema. Should not be too hard, but my laptop is dying and I can't charge it on the boat sadly. heh

But this is good news @Ignalina !! Arrow2 FTW :D

**Comment by Ignalina** [comment]
> I think that to actually see if the 'bridge' between go and Rust works as it should, which it kinda does; we need to read a real array or schema from file, read it in Go, convert all fields to the Cstruct and then pass it as we do.
> 
> @Ignalina do you know how to write a REAL/accurate schema to file that we can use for this?
> 
> If you see the latest commit on branch rewrite/all , compile and run it you will see that it atempts to convert to Schema in Rust, but the C struct is invalid format. Something I'm doing with the export is wrong. Maybe it will be solved if we give it a real schema...
> 
> ALso, will try with arrow2 functions for importing the schema; maybe that will work.
> 
> Have a good weekend, sent from a boat boat
I always wanted to have a yacht too , have fun !

Good idea, ill look at the schema+data. The examples copied from Arrows Go doc woks but maybee i did miss something. 
Guess its time i add a Thund step that sends ArrowChunks vi alloy, I migh tnick something from the repos shredder/fix2arrow thats reads avro schema in json form --> arrow schema.

Did you got this link with C->Arrow2 ?  im focusing to get it working in the develop/rust branch.
Its an array of ArrowArrays = chunks with a fixed datatype.

https://users.rust-lang.org/t/what-to-do-when-nothing-is-implemented-to-resolve-e0507/82505

pub unsafe extern "C" fn from_chunks(arrsptr: *const ffi::ArrowArray, l: usize) {
    let mut cs: Vec<Box<dyn Array>> = Vec::with_capacity(l);

    for index in 0..l {
        cs.push(ffi::import_array_from_c(arrsptr.add(index).read(), DataType::Int64).unwrap())
    }
}

The datatype is fixed, so of course i tried to make it dynamic  , see next function or check out develop/rust branch
I just need to understand 
1) why author used usize and not a simple integer .. perhaps its like  size() for a pointer platform dependent. .. 
2) Create C array with ArrowArray ptr's and ArrosScheme ptrs' 


#[no_mangle]
pub unsafe extern "C" fn from_chunks_ffi(
    arrptr:  *const ffi::ArrowArray,
    schptr: *const ffi::ArrowSchema,
    l: usize
    ) -> c_int {

    println!("Hello2 from Rust!");


    let mut cs: Vec<Box<dyn Array>> = Vec::with_capacity(l);
    for index in 0..l {
            let field = ffi::import_field_from_c(&schptr.add(index).read()).unwrap();
            let array = ffi::import_array_from_c(arrptr.add(index).read(),field.data_type);
            cs.push(array.unwrap());
            cs.push(import(arrptr.add(index).read(),&schptr.add(index).read()).unwrap());

    }
    
    1 as c_int
}

**Comment by Ignalina** [comment]
I'm out of icecream so try to generate the correct C header from the rust code above using https://github.com/eqrion/cbindgen

**Comment by Ignalina** [comment]
check out developer/rust branch it actually woks now.    Had many insights on Rust , its its a lot of details but also VERY good compiler hints.

After merging

I want to release a cargo version (no idea how that woks in rust) , where extend the rust base class could be a static way to add functionality ... or maybee explore a dynamic binding (placing a myimpl.dll alike)  or both ..

go release is easy , just put a tag

**Comment by willeagren** [comment]
WOW! Snyggt Rickard, du är ju värsta Go+C+Rust guden nu ju!! Jag ska ta en titt på branchen, men jag förstår vad du gör med chunksen, smart. Ska fixa syntaxen lite bara.

Innan vi publishar en release på Cargo så tycker jag vi pratar igenom det. Alternativt hur framtiden ser ut; i.e. vilka fler features ska finnas?, vilken funktionalitet bör läggas till?, hur smidigast använder man alloy (definiera en idiomatisk API, både i Go och Rust (?))

VI hörs, bra jobbat! :+1:

**Comment by willeagren** [comment]
En grej förstår jag inte dock.

```
      bld0 := array.NewInt32Builder(mem)
	defer bld0.Release()
	bld0.AppendValues([]int32{122}, []bool{true})
	arr0 := bld0.NewInt32Array() // materialize the array
	defer arr0.Release()

	bld1 := array.NewInt64Builder(mem)
	defer bld1.Release()
	bld1.AppendValues([]int64{122}, []bool{true})
	arr1 := bld1.NewInt64Array() // materialize the array
	defer arr1.Release()
```

Vi har ju också ett bool värde i våra arrayer, men dessa syns inte när vi printar dom?, är detta för att:

1) Det är bara en flagga, t.ex. nullable eller dylikt?
2) När man 'bygger'/materialiserar arrayen så tas allt som inte är den datatypen bort?

Mvh, Wilhelm

**Comment by willeagren** [comment]
I am opening a new issue, relating to how we go forward with the Cargo release. (#40)

**Comment by willeagren** [comment]
Tja!

Har lagt till lite ändringar i development/rust, du är ju grym!! Snygt att
de funkar. Kan inte merga med master dock, för ligger en del ändringar i
README osv. Men ska lösa det här ikväll när jag åker båten.

/Mvh WIlhelm

Den sön 16 okt. 2022 kl 03:43 skrev Rickard Ernst Björn Lundin <
***@***.***>:
