### ISSUE TITLE
Dynamically sending x number of array (chunks)

### ISSUE THREAD

**Issue by willeagren** [Ignalina/alloy#42]
On branch feature/rust I am trying to make a Go example where we dynamically send x number of arrays to Rust, could represent reading parquets of different sizes, yielding different number of arrays.

But when running I get the Cgo error that an argument has Go pointer to Go pointer... Doesn't make a whole lot of sense since the code more or less does the exact same ffi stuff as the working example.

But need help :)

```
[Go]	Calling the goBridge with:
	[[1 2 3 -4] [1 2 3 -4]]
[Go]	Exporting schema+array #1
[Go]	Exporting schema+array #2
[Go]	Calling Rust through C ffi now...
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/ignalina/alloy/cdata.GoBridge.Call.func1(0xc0000121b0, 0xc000014018?)
	/home/eli/Coding/alloy/cdata/call.go:42 +0x4b
github.com/ignalina/alloy/cdata.GoBridge.Call({0x987920?}, {0xc000016fc0, 0x2, 0x24?})
	/home/eli/Coding/alloy/cdata/call.go:43 +0x315
main.main()
	/home/eli/Coding/alloy/main.go:42 +0x313
```

**Comment by willeagren** [comment]
Somewhere there is a go-pointer-to-go-pointer... Please help me find it, hehe

```
func (goBridge GoBridge) Call(arrays []*array.Int32) (int, error) {
    var carrowschemas []cdata.CArrowSchema
    var carrowarrays []cdata.CArrowArray
    for idx, array := range arrays {
        fmt.Printf("[Go]\tExporting schema+array #%v\n", idx + 1)
        cas := cdata.CArrowSchema{}
        caa := cdata.CArrowArray{}
        cdata.ExportArrowArray(array, &caa, &cas)
        carrowschemas = append(carrowschemas, cas)
        carrowarrays = append(carrowarrays, caa)
    }

    fmt.Printf("[Go]\tCalling Rust through C ffi now...\n")
    ret := C.call_with_ffi_voidptr(
        unsafe.Pointer(&carrowschemas),
        unsafe.Pointer(&carrowarrays),
        C.uintptr_t(len(carrowschemas)),
    )

    fmt.Printf("[Go]\tHello, again! Successfully sent Arrow data to Rust.\n")
    return int(ret), nil
}
```

**Comment by willeagren** [comment]
When changing to this as arguments to the C function it works.
```
    ret := C.call_with_ffi_voidptr(
        unsafe.Pointer(&Cschemas[0]),
        unsafe.Pointer(&Carrays[0]),
        C.uintptr_t(1),
    )
```

So evidently the go-pointer-to-go-pointer occurs when we try to give the address to the array containing the C_structs (carrowschemas and carrowarrays). But what is different here from the working example? Aha! I think I got it, since we are increasing the address index based on the argument 'how many arrays are there' we CAN NOT send a list of them, only send the first occurrance in the list and the usize saying for how long we can read memory until we reach un-allocated memory! Lets try

**Comment by willeagren** [comment]
It does work! Haha, when you start using your brain the code starts working as well.. haha... Summary: coding on a boat does not provide you more brainpower, only makes you a worse programmer... :boat:

**Comment by Ignalina** [comment]
Good boat wok !
