### ISSUE TITLE
create instance of OneShot with DummyBackend as fallback

### ISSUE THREAD

**Issue by Ignalina** [Ignalina/alloy#45]
Mighty Rust @willeagren help me make a load(ddlname) .so file and create instance of OneShot with DummyBackend as fallback (no ddlname given)

file: https://github.com/Ignalina/alloy/blob/main/ffi/rust/src/lib.rs

    let  db: DummyBackend = DummyBackend{ ddlname: String::from("dummy") };
    db.from_chunks(arrays) as c_uint

**Comment by Ignalina** [comment]
This gonna be glorius !

**Comment by willeagren** [comment]
I will look at this when I have the time, maybe this weekend :)
