### ISSUE TITLE
Set up githubs workflow for build-testing on PR/merge/push?

### ISSUE THREAD

**Issue by willeagren** [Ignalina/alloy#6]
We could set up a number of workflows; one that compiles the Rust code and lets us know the compete status of that on multiple systems (when PR, merge, or even push).

One separate for Go, making sure that it runs as it should, with the provided dependencies. 

Maybe also one complete, which obviously, won't run unless the other language specific workflows complete.

Its easy to expand upon, and I could create a PR with a Rust build workflow tonight real quick :)

**Comment by willeagren** [comment]
Go build works with the Makefile and when running `go build ./...` locally, however, fails during the github/workflows.... Look into this.

**Comment by willeagren** [comment]
@Ignalina did your latest commit to the Go workflows (#21) resolve the build issues? The push didn't run the workflow for some reason, so we could make a dummy PR and check the status on that.

**Comment by Ignalina** [comment]
I prob mixed up the branches , acting as a chaos monkey trying to figure out the ui :) which is not always bad https://en.m.wikipedia.org/wiki/Chaos_engineering

Where is the ”run my pipeline” button :) ???

/mvh Rickard

Skickat från min iPhone

2 okt. 2022 kl. 09:49 skrev Wilhelm Ågren ***@***.***>:

﻿

@Ignalina<https://github.com/Ignalina> did your latest commit to the Go workflows (#21<https://github.com/Ignalina/alloy/pull/21>) resolve the build issues? The push didn't run the workflow for some reason, so we could make a dummy PR and check the status on that.

**Comment by willeagren** [comment]
Run my pipeline? on Jenkins? I will look into commit history of the Jenkinsfile. Will return.

**Comment by willeagren** [comment]
I can run on jenkins. Maybe I didn't understand the issue.

**Comment by willeagren** [comment]
I think that all of the necessary workflows for builds and tests have been correctly implemented and merged. Closing issue. See latest merge #34.
